<?php

return (object) array(
   '11' => 
  (object) array(
     'en' => '11th Step Meditation',
     'es' => 'Meditación del Paso 11',
     'fr' => 'Méditation sur la 11e Étape',
     'ja' => 'ステップ11 黙想',
     'nl' => 'Stap 11 meditatie',
     'pt' => 'Meditação do 11º Passo',
     'sk' => 'Meditácia 11. kroku',
     'sv' => '11th Stegs Meditation',
  ),
   '12x12' => 
  (object) array(
     'en' => '12 Steps & 12 Traditions',
     'es' => '12 Pasos y 12 Tradiciones',
     'fr' => '12 Étapes et 12 Traditions',
     'ja' => '12のステップと12の伝統',
     'nl' => '12 Stappen en 12 Tradities',
     'pt' => '12 Passos e 12 Tradições',
     'sk' => '12 Krokov & 12 Tradícií',
     'sv' => '12 Steg & 12 Traditioner',
  ),
   'A' => 
  (object) array(
     'en' => 'Secular',
     'es' => 'Secular',
     'fr' => 'Séculier',
     'ja' => '無宗教',
     'nl' => 'Seculier',
     'pt' => 'Secular',
     'sk' => 'Svetské',
     'sv' => 'Sekulärt',
  ),
   'ABSI' => 
  (object) array(
     'en' => 'As Bill Sees It',
     'es' => 'Como lo ve Bill',
     'fr' => 'Réflexions de Bill',
     'ja' => 'ビルはこう思う',
     'nl' => 'Zoals Bill het ziet',
     'pt' => 'Na opinião de Bill',
     'sk' => 'Ako to vidí Bill',
     'sv' => 'Som Bill Ser Det',
  ),
   'AL' => 
  (object) array(
     'en' => 'Concurrent with Alateen',
     'es' => 'Concurrente con Alateen',
     'fr' => 'En même temps qu’Alateen',
     'ja' => 'アラティーンと同時進行',
     'nl' => 'Gelijktijdig met Alateen',
     'pt' => 'Em simultâneo com Alateen',
     'sk' => 'Súbežne s Alateen',
     'sv' => 'Tillsammans med Alateen',
  ),
   'AL-AN' => 
  (object) array(
     'en' => 'Concurrent with Al-Anon',
     'es' => 'Concurrente con Al-Anon',
     'fr' => 'En même temps qu’Al-Anon',
     'ja' => 'アラノンと同時進行',
     'nl' => 'Gelijktijdig met Al-Anon',
     'pt' => 'Em simultâneo com Al-Anon',
     'sk' => 'Súbežne s Al-Anon',
     'sv' => 'Tillsammans med Al-Anon',
  ),
   'AM' => 
  (object) array(
     'en' => 'Amharic',
     'es' => 'Amárico',
     'fr' => 'Amharique',
     'ja' => 'アムハラ語',
     'nl' => 'Amhaars',
     'pt' => 'Amárico',
     'sk' => 'Amharčina',
     'sv' => 'Amhariska',
  ),
   'ASL' => 
  (object) array(
     'en' => 'American Sign Language',
     'es' => 'Lenguaje por señas',
     'fr' => 'Langage des Signes',
     'ja' => 'アメリカ手話',
     'nl' => 'Amerikaanse gebaren taal',
     'pt' => 'Língua Gestual Americana',
     'sk' => 'Americký posunkový jazyk',
     'sv' => 'Amerikanskt teckenspråk',
  ),
   'B' => 
  (object) array(
     'en' => 'Big Book',
     'es' => 'Libro Grande',
     'fr' => 'Gros Livre',
     'ja' => 'ビッグブック',
     'nl' => 'Big Book',
     'pt' => 'Livro Azul',
     'sk' => 'Veľká Kniha',
     'sv' => 'Stora Boken',
  ),
   'BA' => 
  (object) array(
     'en' => 'Babysitting Available',
     'es' => 'Guardería disponible',
     'fr' => 'Garderie d’enfants disponible',
     'ja' => 'ベビーシッターあり',
     'nl' => 'Kinderopvang aanwezig',
     'pt' => 'Babysitting disponível',
     'sk' => 'Dostupné opatrovanie detí',
     'sv' => 'Barnvakt Finns',
  ),
   'BE' => 
  (object) array(
     'en' => 'Newcomer',
     'es' => 'Principiantes',
     'fr' => 'Nouveau/nouvelle',
     'ja' => 'ビギナーズ',
     'nl' => 'Nieuwkomer',
     'pt' => 'Recém-chegados',
     'sk' => 'Nováčikovia',
     'sv' => 'Nykomling',
  ),
   'BI' => 
  (object) array(
     'en' => 'Bisexual',
     'es' => 'Bisexual',
     'fr' => 'Bisexuel',
     'ja' => 'バイセクシャル',
     'nl' => 'Biseksueel',
     'pt' => 'Bisexual',
     'sk' => 'Bisexuálne',
     'sv' => 'Bisexuellt',
  ),
   'BRK' => 
  (object) array(
     'en' => 'Breakfast',
     'es' => 'Desayuno',
     'fr' => 'Petit déjeuner',
     'ja' => '朝食',
     'nl' => 'Ontbijt',
     'pt' => 'Pequeno-Almoço',
     'sk' => 'Raňajky',
     'sv' => 'Frukost',
  ),
   'C' => 
  (object) array(
     'en' => 'Closed',
     'es' => 'Cerrada',
     'fr' => 'Fermé',
     'ja' => 'クローズド',
     'nl' => 'Gesloten',
     'pt' => 'Fechada',
     'sk' => 'Uzatvorené',
     'sv' => 'Slutet',
  ),
   'CAN' => 
  (object) array(
     'en' => 'Candlelight',
     'es' => 'Luz de una vela',
     'fr' => 'À la chandelle',
     'ja' => 'キャンドル',
     'nl' => 'Candlelight',
     'pt' => 'Luz de Velas',
     'sk' => 'Sviečky',
     'sv' => 'Tända Ljus',
  ),
   'CF' => 
  (object) array(
     'en' => 'Child-Friendly',
     'es' => 'Niño amigable',
     'fr' => 'Enfants acceptés',
     'ja' => 'お子さま歓迎',
     'nl' => 'Kindvriendelijk',
     'pt' => 'Amigável para Crianças',
     'sk' => 'Priateľský k deťom',
     'sv' => 'Barnvänligt',
  ),
   'D' => 
  (object) array(
     'en' => 'Discussion',
     'es' => 'Discusión',
     'fr' => 'Discussion',
     'ja' => 'ディスカッション',
     'nl' => 'Discussie',
     'pt' => 'Discussão',
     'sk' => 'Diskusia',
     'sv' => 'Diskussion',
  ),
   'DA' => 
  (object) array(
     'en' => 'Danish',
     'es' => 'Danés',
     'fr' => 'Danois',
     'ja' => 'デンマーク語',
     'nl' => 'Deens',
     'pt' => 'Dinamarquês',
     'sk' => 'Dánsky',
     'sv' => 'Danska',
  ),
   'DB' => 
  (object) array(
     'en' => 'Digital Basket',
     'es' => 'Canasta digital',
     'fr' => 'Panier numérique',
     'ja' => '電子献金',
     'nl' => 'Digitale mand',
     'pt' => 'Cesto Digital',
     'sk' => 'Digitálny košík',
     'sv' => 'Digital Korg',
  ),
   'DD' => 
  (object) array(
     'en' => 'Dual Diagnosis',
     'es' => 'Diagnóstico dual',
     'fr' => 'Double diagnostic',
     'ja' => '重複診断',
     'nl' => 'Dubbele diagnose',
     'pt' => 'Duplo Diagnóstico',
     'sk' => 'Duálna diagnóza',
     'sv' => 'Dubbel Diagnos',
  ),
   'DE' => 
  (object) array(
     'en' => 'German',
     'es' => 'Alemán',
     'fr' => 'Allemand',
     'ja' => 'ドイツ語',
     'nl' => 'Duits',
     'pt' => 'Alemão',
     'sk' => 'Nemecké',
     'sv' => 'Tyska',
  ),
   'DR' => 
  (object) array(
     'en' => 'Daily Reflections',
     'es' => 'Reflexiones Diarias',
     'fr' => 'Réflexions quotidiennes',
     'ja' => '今日を新たに',
     'nl' => 'Dagelijkse weerspiegelingen',
     'pt' => 'Reflexões Diárias',
     'sv' => 'Dagliga Reflektioner',
     'sk' => 'Denné úvahy',
  ),
   'EL' => 
  (object) array(
     'en' => 'Greek',
     'es' => 'Griego',
     'fr' => 'Grec',
     'ja' => 'ギリシャ語',
     'nl' => 'Grieks',
     'pt' => 'Grego',
     'sk' => 'Grécke',
     'sv' => 'Grekiska',
  ),
   'EN' => 
  (object) array(
     'en' => 'English',
     'es' => 'Inglés',
     'fr' => 'Anglais',
     'ja' => '英語',
     'nl' => 'Engels',
     'pt' => 'Inglês',
     'sk' => 'Anglické',
     'sv' => 'Engelska',
  ),
   'FA' => 
  (object) array(
     'en' => 'Persian',
     'es' => 'Persa',
     'fr' => 'Persan',
     'ja' => 'ペルシア語',
     'nl' => 'Perzisch',
     'pt' => 'Persa',
     'sk' => 'Perzské',
     'sv' => 'Persiska',
  ),
   'FF' => 
  (object) array(
     'en' => 'Fragrance Free',
     'es' => 'Sin fragancia',
     'fr' => 'Sans parfum',
     'ja' => '香水なし',
     'nl' => 'Geen parfum',
     'pt' => 'Sem Perfumes',
     'sk' => 'Bez vône',
     'sv' => 'Parfym Fritt',
  ),
   'FR' => 
  (object) array(
     'en' => 'French',
     'es' => 'Francés',
     'fr' => 'Français',
     'ja' => 'フランス語',
     'nl' => 'Frans',
     'pt' => 'Francês',
     'sk' => 'Francúzsky',
     'sv' => 'Franska',
  ),
   'G' => 
  (object) array(
     'en' => 'Gay',
     'es' => 'Gay',
     'fr' => 'Gai',
     'ja' => 'ゲイ',
     'nl' => 'Homo',
     'pt' => 'Gay',
     'sk' => 'Gay',
     'sv' => 'Gay',
  ),
   'GR' => 
  (object) array(
     'en' => 'Grapevine',
     'es' => 'La Viña',
     'fr' => 'Grapevine',
     'ja' => 'グレープバイン',
     'nl' => 'Wijnstok',
     'pt' => 'Grapevine',
     'sk' => 'Grapevine',
     'sv' => 'Grapevine',
  ),
   'H' => 
  (object) array(
     'en' => 'Birthday',
     'es' => 'Cumpleaños',
     'fr' => 'Anniversaire',
     'ja' => 'バースデー',
     'nl' => 'Verjaardag',
     'pt' => 'Aniversário',
     'sk' => 'Narodeniny',
     'sv' => 'Födelsedag',
  ),
   'HE' => 
  (object) array(
     'en' => 'Hebrew',
     'es' => 'Hebreo',
     'fr' => 'Hébreu',
     'ja' => 'ヘブライ語',
     'nl' => 'Hebreeuws',
     'pt' => 'Hebreu',
     'sk' => 'Hebrejské',
     'sv' => 'Hebreiska',
  ),
   'HI' => 
  (object) array(
     'en' => 'Hindi',
     'es' => 'Hindi',
     'fr' => 'Hindi',
     'ja' => 'ヒンディー語',
     'nl' => 'Hindi',
     'pt' => 'Hindi',
     'sk' => 'Hindi',
     'sv' => 'Hindi',
  ),
   'HR' => 
  (object) array(
     'en' => 'Croatian',
     'es' => 'Croata',
     'fr' => 'Croate',
     'ja' => 'クロアチア語',
     'nl' => 'Kroatisch',
     'pt' => 'Croata',
     'sk' => 'Chorvátsky',
     'sv' => 'Kroatiska',
  ),
   'HU' => 
  (object) array(
     'en' => 'Hungarian',
     'es' => 'Húngaro',
     'fr' => 'Hongrois',
     'ja' => 'ハンガリー語',
     'nl' => 'Hongaars',
     'pt' => 'Hungaro',
     'sk' => 'Maďarské',
     'sv' => 'Ungerska',
  ),
   'ITA' => 
  (object) array(
     'en' => 'Italian',
     'es' => 'Italiano',
     'fr' => 'Italien',
     'ja' => 'イタリア語',
     'nl' => 'Italiaans',
     'pt' => 'Italiano',
     'sk' => 'Taliansky',
     'sv' => 'Italienska',
  ),
   'JA' => 
  (object) array(
     'en' => 'Japanese',
     'es' => 'Japonés',
     'fr' => 'Japonais',
     'ja' => '日本語',
     'nl' => 'Japans',
     'pt' => 'Japonês',
     'sk' => 'Japonské',
     'sv' => 'Japanska',
  ),
   'KOR' => 
  (object) array(
     'en' => 'Korean',
     'es' => 'Coreano',
     'fr' => 'Coréen',
     'ja' => '韓国語',
     'nl' => 'Koreaans',
     'pt' => 'Coreano',
     'sk' => 'Kórejske',
     'sv' => 'Koreanska',
  ),
   'L' => 
  (object) array(
     'en' => 'Lesbian',
     'es' => 'Lesbiana',
     'fr' => 'Lesbienne',
     'ja' => 'レズビアン',
     'nl' => 'Lesbisch',
     'pt' => 'Lésbica',
     'sk' => 'Lesbické',
     'sv' => 'Lesbiskt',
  ),
   'LGBTQ' => 
  (object) array(
     'en' => 'LGBTQ',
     'es' => 'LGBTQ',
     'fr' => 'LGBTQ',
     'ja' => 'LGBTQ',
     'nl' => 'LGBTQ',
     'pt' => 'LGBTQ',
     'sk' => 'LGBTQ',
     'sv' => 'HBTQ',
  ),
   'LIT' => 
  (object) array(
     'en' => 'Literature',
     'es' => 'Literatura',
     'fr' => 'Publications',
     'ja' => '書籍',
     'nl' => 'Literatuur',
     'pt' => 'Literatura',
     'sk' => 'Literatúra',
     'sv' => 'Litteratur',
  ),
   'LS' => 
  (object) array(
     'en' => 'Living Sober',
     'es' => 'Viviendo Sobrio',
     'fr' => 'Vivre… Sans alcool',
     'ja' => 'リビングソーバー',
     'nl' => 'Sober leven',
     'pt' => 'Viver Sóbrio',
     'sk' => 'Triezvy život',
     'sv' => 'Leva Nyktert',
  ),
   'LT' => 
  (object) array(
     'en' => 'Lithuanian',
     'es' => 'Lituano',
     'fr' => 'Lituanien',
     'ja' => 'リトアニア語',
     'nl' => 'Litouws',
     'pt' => 'Lituano',
     'sk' => 'Litovské',
     'sv' => 'Litauiska',
  ),
   'M' => 
  (object) array(
     'en' => 'Men',
     'es' => 'Hombres',
     'fr' => 'Hommes',
     'ja' => '男性',
     'nl' => 'Mannen',
     'pt' => 'Homens',
     'sk' => 'Muži',
     'sv' => 'Mansmöte',
  ),
   'MED' => 
  (object) array(
     'en' => 'Meditation',
     'es' => 'Meditación',
     'fr' => 'Méditation',
     'ja' => '黙想',
     'nl' => 'Meditatie',
     'pt' => 'Meditação',
     'sk' => 'Meditácia',
     'sv' => 'Meditationsmöte',
  ),
   'ML' => 
  (object) array(
     'en' => 'Malayalam',
     'es' => 'Malayalam',
     'fr' => 'Malayalam',
     'ja' => 'マラヤーラム語',
     'nl' => 'Malayalam',
     'pt' => 'Malaiala',
     'sk' => 'Malajálamsky',
     'sv' => 'Malayalam',
  ),
   'N' => 
  (object) array(
     'en' => 'Native American',
     'es' => 'Nativo Americano',
     'fr' => 'Autochtone',
     'ja' => 'ネイティブアメリカン',
     'nl' => 'Indiaan',
     'pt' => 'Nativo Americano',
     'sk' => 'Domorodí Američania',
     'sv' => 'Ur-amerikanskt',
  ),
   'NB' => 
  (object) array(
     'en' => 'Non-Binary',
     'es' => 'No binario',
     'fr' => 'Non binaire',
     'ja' => 'ノンバイナリー',
     'nl' => 'Niet-binair',
     'pt' => 'Não binário',
     'sk' => 'Nebinárne',
     'sv' => 'Icke-binär',
  ),
   'NDG' => 
  (object) array(
     'en' => 'Indigenous',
     'es' => 'Indígena',
     'fr' => 'Indigène',
     'ja' => '先住民',
     'nl' => 'Inheems',
     'pt' => 'Indígena',
     'sk' => 'Domorodé',
     'sv' => 'Urfolkligt',
  ),
   'NO' => 
  (object) array(
     'en' => 'Norwegian',
     'es' => 'Noruego',
     'fr' => 'Norvégien',
     'ja' => 'ノルウェー語',
     'nl' => 'Noors',
     'pt' => 'Norueguês',
     'sk' => 'Nórsky',
     'sv' => 'Norska',
  ),
   'O' => 
  (object) array(
     'en' => 'Open',
     'es' => 'Abierta',
     'fr' => 'Ouvert(e)',
     'ja' => 'オープン',
     'nl' => 'Open',
     'pt' => 'Aberta',
     'sk' => 'Otvorené',
     'sv' => 'Öppet',
  ),
   'OUT' => 
  (object) array(
     'en' => 'Outdoor',
     'es' => 'Al aire libre',
     'fr' => 'En plein air',
     'ja' => 'アウトドア',
     'nl' => 'Buiten',
     'pt' => 'Ao ar livre',
     'sk' => 'Vonkajšie',
     'sv' => 'Utomhus',
  ),
   'P' => 
  (object) array(
     'en' => 'Professionals',
     'es' => 'Profesionales',
     'fr' => 'Professionnels',
     'ja' => '職業人',
     'nl' => 'Professionals',
     'pt' => 'Profissionais',
     'sk' => 'Profesionáli',
     'sv' => 'Professionella',
  ),
   'POA' => 
  (object) array(
     'en' => 'Proof of Attendance',
     'es' => 'Prueba de Asistencia',
     'fr' => 'Preuve de Présence',
     'ja' => '出席証明',
     'nl' => 'Bewijs van Aanwezigheid',
     'pt' => 'Comprovante de Presença',
     'sk' => 'Doklad o účasti',
     'sv' => 'Närvarobevis',
  ),
   'POC' => 
  (object) array(
     'en' => 'People of Color',
     'es' => 'Gente de color',
     'fr' => 'Gens de couleur',
     'ja' => '有色人種',
     'nl' => 'Mensen van kleur',
     'pt' => 'Pessoas de Côr',
     'sk' => 'Farební ľudia',
     'sv' => 'Färgade',
  ),
   'POL' => 
  (object) array(
     'en' => 'Polish',
     'es' => 'Polaco',
     'fr' => 'Polonais',
     'ja' => 'ポーランド語',
     'nl' => 'Pools',
     'pt' => 'Polaco',
     'sk' => 'Poľské',
     'sv' => 'Polska',
  ),
   'POR' => 
  (object) array(
     'en' => 'Portuguese',
     'es' => 'Portugués',
     'fr' => 'Portugais',
     'ja' => 'ポルトガル語',
     'nl' => 'Portugees',
     'pt' => 'Português',
     'sk' => 'Portugalské',
     'sv' => 'Portugisiska',
  ),
   'PUN' => 
  (object) array(
     'en' => 'Punjabi',
     'es' => 'Punjabi',
     'fr' => 'Pendjabi',
     'ja' => 'パンジャブ語',
     'nl' => 'Punjabi',
     'pt' => 'Punjabi',
     'sk' => 'Pandžábske',
     'sv' => 'Punjabi',
  ),
   'RUS' => 
  (object) array(
     'en' => 'Russian',
     'es' => 'Ruso',
     'fr' => 'Russe',
     'ja' => 'ロシア語',
     'nl' => 'Russisch',
     'pt' => 'Russo',
     'sk' => 'Ruské',
     'sv' => 'Ryska',
  ),
   'S' => 
  (object) array(
     'en' => 'Spanish',
     'es' => 'Español',
     'fr' => 'Espagnol',
     'ja' => 'スペイン語',
     'nl' => 'Spaans',
     'pt' => 'Espanhol',
     'sk' => 'Španielské',
     'sv' => 'Spanska',
  ),
   'SEN' => 
  (object) array(
     'en' => 'Seniors',
     'es' => 'Personas mayores',
     'fr' => 'Séniors',
     'ja' => 'シニア',
     'nl' => 'Senioren',
     'pt' => 'Séniores',
     'sk' => 'Seniori',
     'sv' => 'Seniorer',
  ),
   'SK' => 
  (object) array(
     'en' => 'Slovak',
     'es' => 'Eslovaco',
     'fr' => 'Slovaque',
     'ja' => 'スロバキア語',
     'nl' => 'Slowaaks',
     'pt' => 'Eslovaco',
     'sk' => 'Slovenské',
     'sv' => 'Slovakiska',
  ),
   'SM' => 
  (object) array(
     'en' => 'Smoking Permitted',
     'es' => 'Se permite fumar',
     'fr' => 'Permis de fumer',
     'ja' => '喫煙可',
     'nl' => 'Roken toegestaan',
     'pt' => 'Permitido Fumar',
     'sk' => 'Fajčenie povolené',
     'sv' => 'Rökning Tillåten',
  ),
   'SP' => 
  (object) array(
     'en' => 'Speaker',
     'es' => 'Orador',
     'fr' => 'Conférencier',
     'ja' => 'スピーカー',
     'nl' => 'Spreker',
     'pt' => 'Partilhador',
     'sk' => 'Spíker',
     'sv' => 'Talare',
  ),
   'ST' => 
  (object) array(
     'en' => 'Step Study',
     'es' => 'Estudio de pasos',
     'fr' => 'Sur les Étapes',
     'ja' => 'ステップ',
     'nl' => 'Stap studie',
     'pt' => 'Estudo de Passos',
     'sk' => 'Štúdium Krokov',
     'sv' => 'Stegmöte',
  ),
   'SV' => 
  (object) array(
     'en' => 'Swedish',
     'es' => 'Sueco',
     'fr' => 'Suédois',
     'ja' => 'スウェーデン語',
     'nl' => 'Zweeds',
     'pt' => 'Sueco',
     'sk' => 'Švédske',
     'sv' => 'Svenska',
  ),
   'T' => 
  (object) array(
     'en' => 'Transgender',
     'es' => 'Transgénero',
     'fr' => 'Transgenre',
     'ja' => 'トランスジェンダー',
     'nl' => 'Transgender',
     'pt' => 'Transgénero',
     'sk' => 'Transgender',
     'sv' => 'Transpersoner',
  ),
   'TC' => 
  (object) array(
     'en' => 'Location Temporarily Closed',
     'es' => 'Ubicación temporalmente cerrada',
     'fr' => 'Emplacement temporairement fermé',
     'ja' => '一時的休止中',
     'nl' => 'Locatie tijdelijk gesloten',
     'pt' => 'Local Temporáriamente Encerrado',
     'sk' => 'Miesto dočasne zatvorené',
     'sv' => 'Tillfälligt Stängt',
  ),
   'TH' => 
  (object) array(
     'en' => 'Thai',
     'es' => 'Tailandés',
     'fr' => 'Thaï',
     'ja' => 'タイ語',
     'nl' => 'Thais',
     'pt' => 'Tailandês',
     'sk' => 'Thajské',
     'sv' => 'Thailändska',
  ),
   'TL' => 
  (object) array(
     'en' => 'Tagalog',
     'es' => 'Tagalo',
     'fr' => 'Tagalog',
     'ja' => 'タガログ語',
     'nl' => 'Tagalog',
     'pt' => 'Tagalo',
     'sk' => 'Tagalské',
     'sv' => 'Tagalog',
  ),
   'TR' => 
  (object) array(
     'en' => 'Tradition Study',
     'es' => 'Estudio de tradicion',
     'fr' => 'Étude des Traditions',
     'ja' => '伝統',
     'nl' => 'Traditie Studie',
     'pt' => 'Estudo de Tradições',
     'sk' => 'Tradičné štúdium',
     'sv' => 'Traditionsmöte',
  ),
   'TUR' => 
  (object) array(
     'en' => 'Turkish',
     'es' => 'Turco',
     'fr' => 'Turc',
     'ja' => 'トルコ語',
     'nl' => 'Turks',
     'pt' => 'Turco',
     'sk' => 'Turecký',
     'sv' => 'Turkiska',
  ),
   'UK' => 
  (object) array(
     'en' => 'Ukrainian',
     'es' => 'Ucraniano',
     'fr' => 'Ukrainien',
     'ja' => 'ウクライナ語',
     'nl' => 'Oekraïens',
     'pt' => 'Ucraniano',
     'sk' => 'Ukrajinské',
     'sv' => 'Ukrainska',
  ),
   'W' => 
  (object) array(
     'en' => 'Women',
     'es' => 'Mujer',
     'fr' => 'Femmes',
     'ja' => '女性',
     'nl' => 'Vrouwen',
     'pt' => 'Mulheres',
     'sk' => 'Ženy',
     'sv' => 'Kvinnomöte',
  ),
   'X' => 
  (object) array(
     'en' => 'Wheelchair Access',
     'es' => 'Acceso en silla de ruedas',
     'fr' => 'Accès aux fauteuils roulants',
     'ja' => '車いすアクセス',
     'nl' => 'Toegankelijk voor rolstoelgebruikers',
     'pt' => 'Acesso a Cadeiras de Rodas',
     'sk' => 'Prístup pre vozíčkarov',
     'sv' => 'Handikappanpassat',
  ),
   'XB' => 
  (object) array(
     'en' => 'Wheelchair-Accessible Bathroom',
     'es' => 'Baño accesible para sillas de ruedas',
     'fr' => 'Toilettes accessibles aux fauteuils roulants',
     'ja' => '車いす使用者用トイレ',
     'nl' => 'Rolstoeltoegankelijke badkamer',
     'pt' => 'WC com Acesso a Cadeiras de Rodas',
     'sk' => 'Bezbariérová kúpeľňa',
     'sv' => 'Handikappanpassad WC',
  ),
   'XT' => 
  (object) array(
     'en' => 'Cross Talk Permitted',
     'es' => 'Se permite opinar',
     'fr' => 'Conversation croisée permise',
     'ja' => 'クロストーク可能',
     'nl' => 'Cross-sharen toegestaan',
     'pt' => 'Prtilhas Cruzadas Permitidas',
     'sk' => 'Cross Talk povolený',
     'sv' => 'Kommentarer Tilltåtna',
  ),
   'Y' => 
  (object) array(
     'en' => 'Young People',
     'es' => 'Gente joven',
     'fr' => 'Jeunes',
     'ja' => 'ヤング',
     'nl' => 'Jongeren',
     'pt' => 'Jovens',
     'sk' => 'Mladí ľudia',
     'sv' => 'Young People',
  ),
);
